### PR TITLE
Improve types and fix bugs

### LINKED ISSUE #1: Typing event names and data like typed-emitter
Hey there!
I really want to use a middleware-like event system like this one, but im missing an option to better type the events.
[typed-emitter](https://www.npmjs.com/package/typed-emitter) for reference strictly types event names and corresponding event data.
This library seems to be exactly what i want functionality-wise, big props for that! It was the only library for this purpose i could find thats exactly what i want and not completely dead.
Would be great if this extended type support could be added.
Thanks
(Also, why are you not `await`ing next() in your examples in the readme, even though the handler is async?)

### PR DESCRIPTION
**Pull request by leumasme**
- adds the option to provide a type to ChainEventEmitter which will then automatically type event names and data
- fixes ANY_EVENT error handler
- fixes async event handlers (untested?)

closes #1

### CODE REVIEW

**Comment by leumasme** [comment]
closes #1

File: src/lib/ChainEventEmitter.ts [hunk 1]
```diff
@@ -62,55 +56,36 @@ export class ChainEventEmitter {
...
   }
 
-  emit(event: string, data: any): void {
-    this.checkEventName(event);
+  emit<E extends keyof Events>(event: E, ...data: Parameters<Events[E]>): void {
     if ( event !== ANY_EVENT ) {
-      this.eventEmitter.emit(event, data)
+      this.eventEmitter.emit(event, ...data)
     }
   }
```
Comment (leumasme) [inline src/lib/ChainEventEmitter.ts:82]: Note that this change is breaking if this is kept as a ...spread argument
